### PR TITLE
feature: Adding awesome developer

### PR DESCRIPTION
**Pull request by franciscoh017**

### CODE REVIEW

**Comment by AngelGarcia13** [comment]
Hey @franciscoh017 my bad for the late response, could you reduce the size of your image? 

Use https://tinyjpg.com/

**Comment by franciscoh017** [comment]
> Hey @franciscoh017 my bad for the late response, could you reduce the size of your image?
> 
> Use https://tinyjpg.com/

Done

**Comment by franciscoh017** [comment]
@AngelGarcia13 proceed with the PR please.

**Comment by AngelGarcia13** [comment]
@franciscoh017 ✅ done!

**Pull request merged**
