### PR TITLE
Feature/add vue base app

### PR DESCRIPTION
**Pull request by lewandy**
Vue base app created with vue-cli.

 **-> Libraries**

- Vue router
- Vuex 
- Eslint (standart config)
- PWA support
- SCSS(Node Sass)
- Babel
- Unit tests (Jest)

### CODE REVIEW

**Comment by AngelGarcia13** [comment]
Hey @DannyFeliz is there any Vue community? Would be nice to work the app per framework in their respective communities and then merge a MVP in this main project.

**Comment by lewandy** [comment]
@AngelGarcia13 I think that is good idea.

**Comment by DannyFeliz** [comment]
@AngelGarcia13 As far as I know, the only thing we have is the facebook page [Vue Dominicana](https://www.facebook.com/groups/2022974857757366/) but we don't have an organization on github, so I think I can create one.

**Comment by icodeat9** [comment]
i will be happy to help with the vue project

**Comment by DannyFeliz** [comment]
@angel011 @icodeat9 @lewandy 
Here is the organization
https://github.com/organizations/VueDominicana

I already invited you guys

**Pull request closed without merging**
