### PR TITLE
Adding myself. -adding loanding. -setting scrollbar to skills and des…

### PR DESCRIPTION
**Pull request by juanchinovas**
Adding myself. 
Adding loanding. 
Setting scrollbar to skills and description

### CODE REVIEW

**Comment by robertlluberes** [comment]
Hello Juan, I think it would be nice if you add some visual aids about the changes made and references the Issue that you are closing:

- For visual aids look at this previus PR closed: [PR #13](https://github.com/AngelGarcia13/DominicanWhoCodes/pull/13)

- For reference Issue from PR or commit message: [Closing issues using keywords](https://help.github.com/en/articles/closing-issues-using-keywords)

**Comment by juanchinovas** [comment]
Hey! Robert Thanks.

This request closes the issues #16 , #15 

This is the #16, before of this there was a blank page
loading

This is #15 
horizontal_scroll_skills_before

Prompted the scrollbar when the mouse pointer is hover
horizontal_scroll_skills

**Comment by AngelGarcia13** [comment]
This is dope! Thanks @juanchinovas ... I will check it out in a few hours and let you know! 💯

**Comment by AngelGarcia13** [comment]
@juanchinovas your picture is not in the devs-pics folder, please fix that and commit to ship this nice PR!

**Comment by juanchinovas** [comment]
Ready, the pic is uploaded

**Comment by juanchinovas** [comment]
-fixed #21 
-fixed #7 

|Before|After|
|---|---|
|before_phone_photos|after_phone_photos|

**Comment by AngelGarcia13** [comment]
Fixes #16

**Pull request merged**
