### PR TITLE
Adding Leandro Jiménez

### PR DESCRIPTION
**Pull request by leandrojj13**

### CODE REVIEW

**Comment by AngelGarcia13** [comment]
Hey @leandrojj13 please resolve the conflicts in the developers.json file, put yourself at the end.

**Comment by AngelGarcia13** [comment]
> Hey @leandrojj13 please resolve the conflicts in the developers.json file, put yourself at the end.

Still having conflicts

**Comment by leandrojj13** [comment]
Problem fixed

**Comment by AngelGarcia13** [comment]
> Problem fixed

My bad, I just merged a PR that was first in the queue (#28) from @dionnyprensa.

Please resolve the conflicts again (last time I promise)

**Comment by leandrojj13** [comment]
No problem. The problem is fixed.

**Pull request merged**
